### ISSUE TITLE
Please declare a license for your source

### ISSUE THREAD

**Issue by joakime** [Vswe/SC2#2]
Just find an appropriate license and create a file in the root of your source tree called `LICENSE`.

Choose one from https://opensource.org/licenses

MIT or BSD or Apache License are all popular choices.

That, and you can even answer https://twitter.com/Lanse505/status/795711617166098432 (a few years later)

**Comment by Hanse00** [comment]
Hey Joakim,

As you may have noticed, @Vswe hasn't been active for quite a while.
Before leaving, he gave myself contribution access to the repository, so I can check in code as needed, but not change any settings.

As such, I don't feel comfortable picking a license (Nor do I think it would really be legal for me to do so without @Vswe's say). For now you will have to take that tweet as the closest thing to a license you're going to get.

**Comment by joakime** [comment]
It's a shame.
Forks of this have been relicensed under more restrictive licenses (GPL, Commercial, and Full Ownership have been seen in the wild) all because of the lack of license here.
If @Vswe is comfortable releasing all rights and controls over his code (yes, in direct conflict with his tweet/statement), then so be it.

**Comment by Hanse00** [comment]
I appreciate your concern.

At this time, I don't find it appropriate for myself to re-license work that's only a tiny minority my own, and I have no way to reach out to @Vswe for approval to make a larger change.

As neither himself nor I have done anything to police the licensing of other versions, I think you can de facto consider the license to be as permissive as possible.

I'll consider changing it in the future, but I truly do not think that's my place.

**Comment by Hanse00** [comment]
After much consideration, I've decided to go ahead and add the MIT license to the codebase, as the terms of said license are, as far as I can tell, the same as the wishes of @Vswe.
